type User @table {
  email: String!
  passwordHash: String!
  createdAt: Timestamp!
  firstName: String
  lastName: String
  shippingAddress: String
  billingAddress: String
}

type Product @table {
  name: String!
  price: Float!
  description: String!
  createdAt: Timestamp!
  imageUrl: String
  category: Category
  stockQuantity: Int
}

type Category @table {
  name: String!
  createdAt: Timestamp!
  description: String
}

type CartItem @table {
  user: User!
  product: Product!
  quantity: Int!
  createdAt: Timestamp!
}

type Order @table {
  user: User!
  orderDate: Timestamp!
  totalAmount: Float!
  shippingAddress: String!
  status: String!
}

type OrderItem @table {
  order: Order!
  product: Product!
  quantity: Int!
  priceAtTimeOfOrder: Float!
}